name: bioextremes
channels:
  - conda-forge
dependencies:
  - cdsapi
  - beautifulsoup4
  - numpy
  - requests
  - certifi
  - tqdm
  - h5py
  - pandas
  - matplotlib
  - scikit-learn
  - rasterio
  - cfgrib
  - gdal
  - xarray